apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python-deploy
  labels:
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-python-app
  template:
    metadata:
      labels:
        app: hello-python-app
    spec:
      containers:
      - name: hello-python-container
        image: victormx/abraxas:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
  labels:
    env: dev
spec:
  type: LoadBalancer
  selector:
    app: hello-python-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
