on: push
name: Build
jobs:
  docker:
    name: Build and delivery
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout to master
        uses: actions/checkout@master
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_REPOSITORY }}:latest
 